sentences = {
'instruction':["The goal is to sort numbered tokens in ascending order on the board. Please wait for my instructions to move a token. Ready???? Let's start"],
'compassion':["People say lucky in love unlucky in gaming",
                  "Dont worry sometimes happens",
                  "Dont worry I'm sure you will get better",
                  "I know how you feel, I've been in this situation before"],
'congratulation':["You made a great move", 
                  "Well done, you're playing as I expected",
                  "I really enjoying playing with you"],
'max_attempt':["You've reached the maximum number of attempts, I will move the token for you"],
'timeout':["Time is passing I will provide you assistance again"],
'user_move_back':["could you please move back the token?"],
'robot_move_back':["no worries, I will move the token back"],
'lev_0':["It's your turn, please move a token"],
'lev_1':["Come on. I know you can do it",
         "Remember, The numbers have to be sorted in ascending order",
         "I believe in you!!",
         "Dont be afraid to make a mistake. Do it!!"],
'lev_2':["The solution is on row   ",
         "Look at row   "],
'lev_3':["I'm here to help you   The solution can be one of those:",
         "Why do not try with one of those:"],
'lev_4':["The right token is this one:",
         "The right token to move is:",
         "It's not so difficult. the right token to move is."],
'lev_5':["The token to move is this one.",
         "Take it . and move in the right location"],
'pick_ok':["Yep", "Ok", "Great"],
'pick_no':["Really???", "Are you sure?", "No"]
}
